### ISSUE TITLE
gulp setup-project doesn't work

### ISSUE THREAD

**Issue by isoloviev** [syntaxhighlighter/syntaxhighlighter#378]
I've got the following errors:

Are you sure you want to continue connecting (yes/no)? The authenticity of host 'github.com (192.30.252.130)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
[20:05:27] 'setup-project:clone-repos' errored after 3.76 s
[20:05:27] Error: Command failed: /bin/sh -c git clone 'git@github.com:syntaxhighlighter/brush-delphi.git'
Cloning into 'brush-delphi'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

git clone 'git@github.com:syntaxhighlighter/brush-delphi.git'
    at setup-project.js:35:29
    at tryCatcher (/Users/ivans/RingCentral/syntaxhighlighter/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ivans/RingCentral/syntaxhighlighter/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/ivans/RingCentral/syntaxhighlighter/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/ivans/RingCentral/syntaxhighlighter/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/ivans/RingCentral/syntaxhighlighter/node_modules/bluebird/js/release/promise.js:680:18)
    at Async._drainQueue (/Users/ivans/RingCentral/syntaxhighlighter/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/ivans/RingCentral/syntaxhighlighter/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/ivans/RingCentral/syntaxhighlighter/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
``

**Comment by shirognqi** [comment]
you need to add the Git protocol, but I fix it by this way:
change the key world "git@github.com:" into "https://github.com/" in my local repo, run the command next:
gulp setup-project
enjoy it !

**Comment by alexgorbatchev** [comment]
Should I update the docs to reflect this?

**Comment by appetere** [comment]
Having spent hours today with a similar problem, would be good if the [docs](https://github.com/syntaxhighlighter/syntaxhighlighter/wiki/Building) were updated to include this!

Using `SyntaxHighlighter` v4.0.1 I found I had to modify `setup-project.js`.

The source lines are:
````
const loadRepos = () => loadReposFromCache().error(loadReposFromGitHub).then(R.map(R.pick(['ssh_url', 'name'])));
const cloneRepo = repo => { git(`clone '${repo.ssh_url}'`, REPOS_DIR); }
````
And my replacement lines are:
````
const loadRepos = () => loadReposFromCache().error(loadReposFromGitHub).then(R.map(R.pick(['clone_url', 'name'])));
const cloneRepo = repo => git(`clone ${repo.clone_url}`, REPOS_DIR);
````
Rather important to note the single inverted commas have to be removed round `${repo.clone_url}`, otherwise the https protocol is not recognised.

**Comment by yumetodo** [comment]
Me too.
There is no reason to use ssh to clone, I think.

I hope that @appetere 's fix is accepted

**Comment by alexgorbatchev** [comment]
@appetere good catch! Want to make a PR?
