### ISSUE TITLE
Cannot build 3.0.90

### ISSUE THREAD

**Issue by crazy-max** [syntaxhighlighter/syntaxhighlighter#391]
On Debian Jessie i cannot build the project using the following commands from the README.md :

```
npm install
./node_modules/.bin/bower install
./node_modules/.bin/grunt build
```

On `npm install` i get the following error :

```
npm WARN package.json syntaxhighlighter@3.0.90 No license field.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@2.0.1: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.3.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated lodash@1.2.1: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
\
> node-sass@0.6.7 install /root/syntaxhighlighter-3.0.90/node_modules/node-sass
> node rebuild.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/root/syntaxhighlighter-3.0.90/node_modules/node-sass/rebuild.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.45
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.6.7 install: `node rebuild.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the node-sass@0.6.7 install script 'node rebuild.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/syntaxhighlighter-3.0.90/npm-debug.log
```

```
# node -v
v0.10.45
# npm -v
2.15.1
```

See [npm-debug.txt](https://github.com/syntaxhighlighter/syntaxhighlighter/files/321752/npm-debug.txt)

Thanks!

**Comment by crazy-max** [comment]
I have made a HARD reset on 3.0.90 release on a [forked repo](https://github.com/crazy-max/syntaxhighlighter3) of your project and update to node-sass 3.8.x to solve this issue.
