### ISSUE TITLE
Brush tests are failing.

### ISSUE THREAD

**Issue by ethauvin** [syntaxhighlighter/syntaxhighlighter#392]
I started a [Kotlin Brush](https://github.com/ethauvin/brush-kotlin) module, and noticed that all of the default brush modules are failing tests with something like:

```
> babel-node --only='syntaxhighlighter-*,brush-*' node_modules/.bin/_mocha --opts mocha.opts test.js

/home/travis/build/ethauvin/brush-kotlin/node_modules/mocha/node_modules/glob/glob.js:78
undefined._processingEmitQueue = false;
                               ^

TypeError: Cannot set property '_processingEmitQueue' of undefined
    at Object.<anonymous> (node_modules/mocha/node_modules/glob/glob.js:79:1)
    at Module._compile (module.js:413:34)
    at loader (/home/travis/build/ethauvin/brush-kotlin/node_modules/babel-register/lib/node.js:151:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/travis/build/ethauvin/brush-kotlin/node_modules/babel-register/lib/node.js:161:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules/mocha/lib/utils.js:10:12)
    at Module._compile (module.js:413:34)
```
npm is not really my cup of tea, but I was able to get a little further by changing the `babel-node` command to:

```
babel-node --only='syntaxhighlighter-*,brush-*' node_modules/.bin/mocha --opts mocha.opts test.js
```
Still fails though.

Any help would be greatly appreciated.

**Comment by DawidSadlik** [comment]
I have the same problem and I'm new to node.js:( Any syggestions?

**Comment by bhreinb** [comment]
I would love a solution to this as well as it is blocking me develop a brush for Gherkin
