### ISSUE TITLE
ReferenceError: Promise is not defined during build

### ISSUE THREAD

**Issue by Chrigoh** [syntaxhighlighter/syntaxhighlighter#398]
Hi,

when I try to build syntaxhighlighter.js - I followed the instructions on the corresponding Wiki page, I get the following exception.

`$> gulp build --brushes=all --theme=default

[12:02:03] Requiring external module babel-register
[12:02:08] Using gulpfile ~/syntaxhighlighter/gulpfile.babel.js
[12:02:08] Starting 'build'...
[12:02:08] 'build' errored after 585 μs
[12:02:08] ReferenceError: Promise is not defined
    at bundle (/root/syntaxhighlighter/build/bundle.js:158:10)
    at Gulp.<anonymous> (/root/syntaxhighlighter/build/bundle.js:191:7)
    at module.exports (/root/syntaxhighlighter/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/root/syntaxhighlighter/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/root/syntaxhighlighter/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/root/syntaxhighlighter/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:458:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:945:3`

Cheers
Christian

**Comment by oliverjkb** [comment]
Hi Christian, 
although this might already be a zombie issue but I just had the same problem. 
Here is how to correct it (also for everyone else, getting this error in future):

Step 1: run `npm install es6-promise` in syntaxhighlighter root folder
Step 2: add `require('es6-promise').polyfill();` as the first line of your gulpfile.babel.js file in syntaxhighlighter's root folder

run your commands and enjoy successful build! 

best
Oliver
