### ISSUE TITLE
Setup Error - .project-cache.json

### ISSUE THREAD

**Issue by ma-si** [syntaxhighlighter/syntaxhighlighter#430]
```
$ git clone https://github.com/syntaxhighlighter/syntaxhighlighter.git
$ cd syntaxhighlighter
$ npm install
$ gulp setup-project
```

```
[12:09:37] Starting 'setup-project:clone-repos'...
[12:09:37] 'setup-project:clone-repos' errored after 1.52 ms
[12:09:37] TypeError: loadReposFromCache(...).error is not a function
    at loadRepos
    ...
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '.projects-cache.json'
```

**Comment by ma-si** [comment]
Duplicate #428
