### ISSUE TITLE
Install and setup-project issue

### ISSUE THREAD

**Issue by oliviermeunier** [syntaxhighlighter/syntaxhighlighter#449]
Hi,

The npm install command seemed to to run eternally, I stopped it with Ctrl+C. The setup-project command failed, it does not know "import" instruction... What must I do ? I'm rather a PHP developper ... ^^'

`(master) $ npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN optional dep failed, continuing fsevents@1.2.4
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN optional dep failed, continuing fsevents@1.2.4
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
 
> execSync@1.0.2 install /home/ubuntu/workspace/JS/SyntaxHighlighter/node_modules/codecov/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
npm WARN optional dep failed, continuing fsevents@1.2.4
/
^C
olimeunier:~/workspace/JS/SyntaxHighlighter (master) $ npm update
olimeunier:~/workspace/JS/SyntaxHighlighter (master) $ ./node_modules/gulp/bin/gulp.js setup-project
[07:44:32] Failed to load external module @babel/register
[07:44:32] Failed to load external module babel-register
[07:44:32] Failed to load external module babel-core/register
[07:44:32] Failed to load external module babel/register
/home/ubuntu/workspace/JS/SyntaxHighlighter/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulpHelp from 'gulp-help';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/home/ubuntu/workspace/JS/SyntaxHighlighter/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.execute (/home/ubuntu/workspace/JS/SyntaxHighlighter/node_modules/gulp/node_modules/liftoff/index.js:203:12)
    at module.exports (/home/ubuntu/workspace/JS/SyntaxHighlighter/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:51:3)`

**Comment by oliviermeunier** [comment]
That's ok, sorry, after retrying.

**Comment by oliviermeunier** [comment]
THe setup-project command still says an error : 

$ ./node_modules/gulp/bin/gulp.js setup-project
[08:49:22] Failed to load external module @babel/register
[08:49:22] Requiring external module babel-register
[08:49:28] Using gulpfile ~/workspace/JS/SyntaxHighlighter/gulpfile.babel.js
[08:49:28] Starting 'setup-project:clone-repos'...
[08:49:28] 'setup-project:clone-repos' errored after 1.87 ms
[08:49:28] TypeError: loadReposFromCache(...).error is not a function
    at loadRepos (/home/ubuntu/workspace/JS/SyntaxHighlighter/build/setup-project.js:39:48)
    at Gulp.<anonymous> (/home/ubuntu/workspace/JS/SyntaxHighlighter/build/setup-project.js:48:5)
    at module.exports (/home/ubuntu/workspace/JS/SyntaxHighlighter/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/ubuntu/workspace/JS/SyntaxHighlighter/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/ubuntu/workspace/JS/SyntaxHighlighter/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/ubuntu/workspace/JS/SyntaxHighlighter/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /home/ubuntu/workspace/JS/SyntaxHighlighter/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)

**Comment by yumetodo** [comment]
duplicated #428
