### ISSUE TITLE
"npm install" fails

### ISSUE THREAD

**Issue by archiecobbs** [syntaxhighlighter/syntaxhighlighter#464]
I don't use `npm` normally so I'm not sure how to interpret this error.

In any case, this is on Mac OS X with `npm` installed from homebrew.

```
$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> fsevents@1.2.11 install /Users/archie/proj/syntaxhighlighter/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> execSync@1.0.2 install /Users/archie/proj/syntaxhighlighter/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> node-sass@3.13.1 install /Users/archie/proj/syntaxhighlighter/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-79_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-79_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> phantomjs@1.9.20 install /Users/archie/proj/syntaxhighlighter/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/8p/0wf3hrq15r1b_69y8t4ppx6r0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [==================================------] 84%
Received 9187K total.
Extracting zip contents
Removing /Users/archie/proj/syntaxhighlighter/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/8p/0wf3hrq15r1b_69y8t4ppx6r0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1580509478365/phantomjs-1.9.8-macosx -> /Users/archie/proj/syntaxhighlighter/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/archie/proj/syntaxhighlighter/node_modules/phantomjs/lib/phantom/bin/phantomjs

> core-js@2.6.11 postinstall /Users/archie/proj/syntaxhighlighter/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> ejs@2.7.4 postinstall /Users/archie/proj/syntaxhighlighter/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> node-sass@3.13.1 postinstall /Users/archie/proj/syntaxhighlighter/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/Cellar/node/13.7.0/bin/node /Users/archie/proj/syntaxhighlighter/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/local/Cellar/node/13.7.0/bin/node',
gyp verb cli   '/Users/archie/proj/syntaxhighlighter/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@13.7.0 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 13.7.0
gyp verb command install [ '13.7.0' ]
gyp verb install input version string "13.7.0"
gyp verb install installing version: 13.7.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 13.7.0
gyp verb ensuring nodedir is created /Users/archie/.node-gyp/13.7.0
gyp verb created nodedir /Users/archie/.node-gyp/13.7.0
gyp http GET https://nodejs.org/download/release/v13.7.0/node-v13.7.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v13.7.0/node-v13.7.0-headers.tar.gz
gyp verb extracted file from tarball include/node/common.gypi
gyp verb extracted file from tarball include/node/config.gypi
gyp verb extracted file from tarball include/node/node.h
gyp verb extracted file from tarball include/node/node_api.h
gyp verb extracted file from tarball include/node/js_native_api.h
gyp verb extracted file from tarball include/node/js_native_api_types.h

... a bunch of lines skipped ...

  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/Users/archie/.node-gyp/13.7.0/include/node -I/Users/archie/.node-gyp/13.7.0/src -I/Users/archie/.node-gyp/13.7.0/deps/openssl/config -I/Users/archie/.node-gyp/13.7.0/deps/openssl/openssl/include -I/Users/archie/.node-gyp/13.7.0/deps/uv/include -I/Users/archie/.node-gyp/13.7.0/deps/zlib -I/Users/archie/.node-gyp/13.7.0/deps/v8/include -I../../nan -I../src/libsass/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -std=c++11 -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
../src/create_string.cpp:17:25: error: no matching constructor for initialization of 'v8::String::Utf8Value'
  v8::String::Utf8Value string(value);
                        ^      ~~~~~
/Users/archie/.node-gyp/13.7.0/include/node/v8.h:3187:5: note: candidate constructor not viable: no known conversion from
      'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/archie/.node-gyp/13.7.0/include/node/v8.h:3180:5: note: candidate constructor not viable: requires 2 arguments, but 1 was
      provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 error generated.
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/archie/proj/syntaxhighlighter/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.7.0/bin/node" "/Users/archie/proj/syntaxhighlighter/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/archie/proj/syntaxhighlighter/node_modules/node-sass
gyp ERR! node -v v13.7.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN notsup Unsupported engine for karma@0.13.22: wanted: {"node":"0.10 || 0.12 || 4 || 5"} (current: {"node":"13.7.0","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: karma@0.13.22

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/archie/.npm/_logs/2020-01-31T22_26_24_526Z-debug.log
```

Dumb question: syntaxhighlighter is pure Javascript, right? So can't you provide a version of it that's already built, using some standard configuration (e.g., include all brushes), so people can just download it?

Thanks.

**Comment by mitrakov** [comment]
The same problem.
npm version 6.13.7

**Comment by FryingggPannn** [comment]
I have the same problem too.

**Comment by danielhsy** [comment]
Look at the top answer here:
https://stackoverflow.com/questions/61037449/npm-building-issues-for-syntaxhighlighter

**Comment by steven-ponessa** [comment]
It would be helpful this repo came with a pre-built version.  I understand from the stackoverflow answer above that I would need to build this under Node 5 however IBM Api Connect has an issue running on a Mac where the node version is controlled by NVM.  I don't know if the Api Connect issue has been resolved, but I know that I don't have the time or inclination to install NVM, Node 5, deinstall Node 5 and NVM.  It is a shame because I like the look and line numbers in syntax highlighter.

As an edit, I did manage to quickly generate the syntaxhighlighter.js file using a Docker container.  In the cloned directory I added the Dockerfile.
```
FROM node:5
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .
```
Thereafter I was able to:

1. Build a local docker container
```
docker build -t syntaxhighlighter .
```
2. Run the container mapping my local `dist` directory to the container's `dist` directory
```
docker run -i --volume ~/github/syntaxhighlighter/dist:/usr/src/app/dist syntaxhighlighter
```
3. Got the container id for the local running container 
```
docker ps
```
4. Used the container id to go into the container (could have also just put `CMD ['/bin/sh']` in my Dockerfile)
```
docker exec -it <the-container-id> /bin/sh
```
5. Ran the gulp build from the Node v5 container.  Since I am mapping my local  `dist` directory to the container's `dist` directory, I get the output locally.
```
./node_modules/gulp/bin/gulp.js build --brushes=all  --compat
```

**Comment by DManstrator** [comment]
@steven-ponessa Thank you very much, the Dockerfile helped me to get the files. I still had a very hard time so I want to give some addtional feedback for people also trying it.

First of all: Use https://github.com/BartJolling/syntaxhighlighter instead, I'll explain later and you will save your time.

1. First problems already started when running the Docker container. The mounting didn't work at all for serveral reasons.
    - You have to add the path of your computer which should be mounted in `Settings > Docker > Resources > File sharing`.
    - You might need to pass an absolute path instead of using `~`. I ended up starting the container with
      ` docker run -i -v C:/Users/<username>/[...]/syntaxhighlighter/dist:/usr/src/app/dist syntaxhighlighter`
    - Note that this is a blocking call since it will start / run the container, for further stuff you need another console.
2. `docker exec [...]` didn't work for me at all. I first tried removing the `t` from `-it` but in the end it couldn't find the `sh` binary. Or better: It found it but it simply didn't work.
```
$ docker exec -i <id> /bin/sh
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "C:/Program Files/Git/usr/bin/sh": stat C:/Program Files/Git/usr/bin/sh: no such file or directory: unknown
```
2. Since you also have to mount the directory, I just recommend you to use the Docker UI.
Go to `Container / Apps`, find the running instance, hover over it and click on `CLI` (should be most left button). Then you have a console for the container executing the following commands.

3. To get the brushes, you need to execute `./node_modules/gulp/bin/gulp.js setup-project` first. It is in the Wiki but I didn't find it at first. This will also download the themes.
    - Doing this will not work though. As mentioned above, you should use https://github.com/BartJolling/syntaxhighlighter instead. It is a fork of a fork fixing several issues as mentioned in [this StackOverflow answer](https://stackoverflow.com/a/67080860).

4. Finally create the `syntaxhighlighter.js`. For this I recommend to add a theme too since there are no default values. To use the default theme, simply use `./node_modules/gulp/bin/gulp.js build --brushes=all --theme=default --compat`
    - If you know you only need one or two brushes, just use them instead of `all`. See the [building wiki](https://github.com/syntaxhighlighter/syntaxhighlighter/wiki/Building#--brushes) for more information.

And in the end, it finally worked and I had an example file at `dist/index.html`. :)

![image](https://user-images.githubusercontent.com/7572614/123448197-f2525180-d5da-11eb-8ecd-4e152585797f.png)

So, thanks again and I hope my post also helps. :D
